// Local interactive tester for Ask Rumbly -- loads real data once at
// startup, then serves a single HTML page (public/index.html) with a text
// box. No app, no Simulator, no rebuild between queries, and (since
// 2026-07-31) no model call either -- classification is the pure-TS
// semantic QueryPlan path, so this responds instantly instead of waiting on a
// Swift subprocess. A legacy comparison mode remains available in the page.
// Meant for the project owner to type queries directly
// rather than the agent guessing phrasings alone.
//
// Usage: node --import ./register-loader.mjs server.ts
//        node --import ./register-loader.mjs server.ts --refresh   # bypass 24h data cache
// Then open http://localhost:8420

import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadData } from './data.ts';
import { answerQuery, type ClassifiedQuery } from './executor.ts';
import { classifyRuleBased } from './rule_classifier.ts';
import { suggestEntities } from './entity_suggestions.ts';
import { continueAskRumbly, runAskRumbly } from '../../../../src/askRumbly/appExecutor.ts';
import { isQueryPlanRefinement } from '../../../../src/askRumbly/queryRefinement.ts';
import type { QueryPlan, QueryPlanRefinement } from '../../../../src/askRumbly/queryPlan.ts';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const PORT = 8420;
const MAX_BODY_BYTES = 16 * 1024;
const MAX_QUERY_LENGTH = 500;

console.log('Loading real restaurant/menu data (cached 24h, use --refresh to bypass)...');
const data = await loadData({ refresh: process.argv.includes('--refresh') });
console.log(`Loaded ${data.restaurants.length} restaurants, ${data.menuItems.length} menu items.`);

let examples: unknown = {};
try {
  examples = JSON.parse(readFileSync(join(scriptDir, 'test-prompts.json'), 'utf8'));
} catch {
  // optional
}

const indexHtml = readFileSync(join(scriptDir, 'public', 'index.html'), 'utf8');

const server = createServer((req, res) => {
  if (req.method === 'GET' && req.url === '/') {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(indexHtml);
    return;
  }
  if (req.method === 'GET' && req.url === '/examples') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(examples));
    return;
  }
  if (req.method === 'GET' && req.url?.startsWith('/suggest?')) {
    const url = new URL(req.url, 'http://localhost');
    const query = url.searchParams.get('q') ?? '';
    const suggestions = query.length <= MAX_QUERY_LENGTH ? suggestEntities(query, data) : [];
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ suggestions }));
    return;
  }
  if (req.method === 'POST' && req.url === '/ask') {
    let body = '';
    let bodyBytes = 0;
    req.on('data', (chunk: Buffer) => {
      bodyBytes += chunk.length;
      if (bodyBytes > MAX_BODY_BYTES) {
        res.writeHead(413, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Request body is too large.' }));
        req.destroy();
        return;
      }
      body += chunk.toString('utf8');
    });
    req.on('end', () => {
      if (res.writableEnded) return;
      try {
        const payload = JSON.parse(body) as { query?: unknown; classified?: unknown; plan?: unknown; refinement?: unknown; mode?: unknown };
        const startedAt = Date.now();
        let classified: ClassifiedQuery | null = null;
        let plan: QueryPlan | null = null;
        let architecture = 'semantic';
        let result;
        if (payload.plan && typeof payload.plan === 'object' && isQueryPlanRefinement(payload.refinement)) {
          // Typed semantic continuations preserve the original scope and every
          // unrelated constraint, then re-enter capability, execution, and
          // proof. They are never regenerated as prose.
          const refinement = payload.refinement as QueryPlanRefinement;
          const option = { id: `tester:${refinement.kind}:${refinement.value}`, label: String(refinement.value), refinement };
          const response = continueAskRumbly(payload.plan as QueryPlan, option, data);
          plan = response.plan;
          architecture = 'semantic-continuation';
          result = response.result;
        } else if (payload.classified && typeof payload.classified === 'object') {
          // Continuation options are generated by this same process and
          // remain subject to executor validation; this lets the tester
          // exercise a clarification round-trip without reparsing prose.
          classified = payload.classified as ClassifiedQuery;
          architecture = 'legacy-continuation';
          result = answerQuery(classified, data);
        } else {
          const query = payload.query;
          if (typeof query !== 'string' || query.trim().length === 0) {
            res.writeHead(400, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: 'query must be a non-empty string.' }));
            return;
          }
          if (query.length > MAX_QUERY_LENGTH) {
            res.writeHead(400, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: `query must be ${MAX_QUERY_LENGTH} characters or fewer.` }));
            return;
          }
          if (payload.mode === 'legacy') {
            architecture = 'legacy';
            classified = classifyRuleBased(query, data);
            result = answerQuery(classified, data);
          } else {
            const response = runAskRumbly(query, data);
            plan = response.plan;
            result = response.result;
          }
        }
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ architecture, classified: plan ?? classified, result, elapsedMs: Date.now() - startedAt }));
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: String(err) }));
      }
    });
    return;
  }
  res.writeHead(404);
  res.end('Not found');
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`Ask Rumbly tester running at http://localhost:${PORT}`);
});
